FROM public.ecr.aws/lambda/python:3.10

COPY ./app ${LAMBDA_TASK_ROOT}/app

COPY requirements.txt .

RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" -U --no-cache-dir

# RUN pip install -r requirements.txt

# ENTRYPOINT ["poetry", "run", "python", "index.py"]
CMD ["app.index.handler"]